### ISSUE TITLE
prison labor dodger

### ISSUE THREAD

**Issue by KondaManjunathSaiPradeep** [rudisimo/google-foobar#6]
Hi 
with your solution, it fails the following testcase:
([1,1,1,1],[1,1,1,1,1,1,1,1]), you have taken eliminating duplicates into consideration. However, you missed out on the number of occurrences of each number.

**Comment by rudisimo** [comment]
Thank you for taking the time report the issue, but the only reason this repository was kept around was for archival purposes.

Cheers!
