### ISSUE TITLE
 prepare the bunnies escape 

### ISSUE THREAD

**Issue by joy2889** [rudisimo/google-foobar#8]
prepare the bunnies escape internal test cases are not running successfully in Foobar Challenge 
Please help me with the code for running internal test cases successfully too!

**Comment by AbhiSaphire** [comment]
Hey @joy2889,
The bunnies escape question is a simple **breadth first search algorithm** with a bit of twist.
As you can only break 1 wall. So you can call bfs from source to destination and change values till 1st wall and then call bfs again from destination to source and change values again till the 1st wall.
If (as the question mentions) the given maze is solvable comparing both the bfs solutions you can get your required minimum distance. Below is a pseudo code how to compare.
```python
for i in range(len(maze)):
	for j in range(len(maze[0])):
		if source_to_dest[i][j] and dest_to_source[i][j]:
			returner = min(source_to_dest[i][j] + dest_to_source[i][j] - 1, returner)
return returner
```
I hope my explanation is somewhat helpful. **[Here is a link to my code which got accepted](https://github.com/AbhiSaphire/Competitive-Programming-Solutions/blob/master/Google-Foobar-Challenge/bunny-prisoner-escape.py)**

**Comment by rudisimo** [comment]
Hey @AbhiSaphire,

Thank you for taking the time to respond to @joy2889. Unfortunately, I cannot provide any support on any of the solutions in this repository. This repository was made public for historical reasons, therefore I won't be correcting any errors found in it.

Sincerely,
Rudy P.

P.S. Good luck, and don't give up! 😄
